### ISSUE TITLE
Container only stays up for 1 minute

### ISSUE THREAD

**Issue by scallopedllama** [rroemhild/docker-ejabberd#148] opened 2017-09-19 15:35 UTC
I've been trying to use this container to run Ejabberd but have only managed to get it to keep the container up for about 1 minute. After that, the container exits 0 with no indication as to why. 

Running the example from the README does not appear to be an issue, I'm running the container with the following command:

```
docker run    --name ejabberd --hostname "xmpp.mydomain.com" \
              -p 5222:5222 \
              -v "$(pwd)/host.pem:/tmp/ssl/host.pem" -v "$(pwd)/host.pem:/tmp/ssl/xmpp_domain.pem" \
              --expose 5280 \
              -v ejabberd-conf:/opt/ejabberd/conf -v ejabberd-ssl:/opt/ejabberd/ssl -v ejabberd-db:/opt/ejabberd/database -v ejabberd-upload:/opt/ejabberd/upload \
              --restart always \
               rroemhild/ejabberd:latest
```
I don't see anything in the log indicating why the container is exiting. It looks to me like the `run.sh start` script is exiting 0 after one minute, possibly because the `ejabberdctl foreground` process returns, causing the `wait` to exit. When I run the container with a shell and manually run `/sbin/run start`, the script exits after one minute but ejabberd continues running.

**Comment by scallopedllama** [comment] 2017-09-19 15:44
Think I'm on to something.

`run.sh` has `set -e` configured. It looks like the `ejabberdctl started` command is timing out. The `ejabberdctl` script gives it 30 x 2s or it returns 1.That being the last function call in the script, causes the script itself to exit 1 and that causes `run.sh` to fail, exiting 1.

**Comment by rroemhild** [comment] 2017-09-19 16:05
Maybe an issue with the config or the mounted volumes. Can you post the log output?

**Comment by scallopedllama** [comment] 2017-09-19 17:21
I think it might be failing because ejabberdctl can't connect to ejabberd's XMLRPC.

I had the XMLRPC ports disabled in the config but even with them turned back on it dies after one minute.

Here is my config file:

```yml
###
###               ejabberd configuration file
###
###

### The parameters used in this configuration file are explained in more detail
### in the ejabberd Installation and Operation Guide.
### Please consult the Guide in case of doubts, it is included with
### your copy of ejabberd, and is also available online at
### http://www.process-one.net/en/ejabberd/docs/

###   =======
###   LOGGING

loglevel: 4
log_rotate_size: 10485760
log_rotate_count: 0
log_rate_limit: 100

## watchdog_admins:
##   - "bob@example.com"

###   ================
###   SERVED HOSTNAMES

hosts:
  - "xmpp.mydomain.com"

##
## route_subdomains: Delegate subdomains to other XMPP servers.
## For example, if this ejabberd serves example.org and you want
## to allow communication with an XMPP server called im.example.org.
##
## route_subdomains: s2s

###   ===============
###   LISTENING PORTS

listen:
  -
    ## XMPP Connections from clients
    port: 5222
    module: ejabberd_c2s
    starttls_required: true
    protocol_options:
      - "no_sslv3"
      - "no_tlsv1"
    ## Note: set max_stanza_size to not-infinity if people are DOS'ing the server
    max_stanza_size: infinity
    shaper: c2s_shaper
    access: c2s
    ciphers: "HIGH:!aNULL:!3DES"

    ## NOTE: Do not enable the ejabberd_s2s_in module

  -
    port: 4560
    module: ejabberd_xmlrpc
    access_commands:
      configure:
        all: []

  -
    ## Admin Portal
    port: 5280
    module: ejabberd_http
    request_handlers: {}
    ## NOTE: "/admin" is reserved for the web_admin: true setting
    web_admin: true
    http_bind: true
    captcha: true
    ## NOTE: SSL is not enabled here as it is encrypted by the outside nginx-proxy
    


###   SERVER TO SERVER
###   If there is no listen for s2s configured, s2s does not do anything.
###   ================
s2s_use_starttls: required
s2s_certfile: "/opt/ejabberd/ssl/host.pem"
s2s_protocol_options:
  - "no_sslv3"
  - "no_tlsv1"
s2s_ciphers: "HIGH:!aNULL:!3DES"


###   ==============
###   AUTHENTICATION

auth_method:
  - ldap

auth_password_format: scram


## LDAP authentication

ldap_servers:
  - "0.0.0.0"
ldap_encrypt: none
ldap_tls_verify: false
ldap_tls_depth: 1
ldap_rootdn: "ROOTDN-HERE"
ldap_password: "PASSWORD"
ldap_deref_aliases: never
ldap_base: "LDAP_BASE"
ldap_uids:
  "uid": "%u"

###   ===============
###   TRAFFIC SHAPERS

shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 1000

###   ====================
###   ACCESS CONTROL LISTS

acl:
  admin:
    user:
      - "admin": "xmpp.mydomain.com"
  local:
    user_regexp: ""

###   ============
###   ACCESS RULES

access:
  ## Maximum number of simultaneous sessions allowed for a single user:
  max_user_sessions:
    all: 10
  ## Maximum number of offline messages that users can have:
  max_user_offline_messages:
    admin: 5000
    all: 5000
  ## This rule allows access only for local users:
  local:
    local: allow
  ## Only non-blocked users can use c2s connections:
  c2s:
    blocked: deny
    all: allow
  ## For C2S connections, all users except admins use the "normal" shaper
  c2s_shaper:
    admin: none
    all: normal
  ## All S2S connections use the "fast" shaper
  s2s_shaper:
    all: fast
  ## Only admins can send announcement messages:
  announce:
    admin: allow
  ## Only admins can use the configuration interface:
  configure:
    admin: allow
  ## Admins of this server are also admins of the MUC service:
  muc_admin:
    admin: allow
  ## Only accounts of the local ejabberd server can create rooms:
  muc_create:
    local: allow
    
  ## All users are allowed to use the MUC service:
  muc:
    all: allow
  ## Only accounts on the local ejabberd server can create Pubsub nodes:
  pubsub_createnode:
    local: allow
  ## In-band registration allows registration of any possible username.
  register:
    all: allow
    
  ## Only allow to register from localhost
  trusted_network:
    loopback: allow
  soft_upload_quota:
    all: 400 # MiB
  hard_upload_quota:
    all: 500 # MiB


language: "en"

###   =======
###   MODULES

modules:
  mod_adhoc: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state:
    queue_chat_states: true
    queue_presence: false
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  ## mod_echo: {}
  ## mod_irc: {}
  mod_http_bind: {}
  ## mod_http_fileserver:
  ##   docroot: "/var/www"
  ##   accesslog: "/var/log/ejabberd/access.log"
  mod_last: {}
  mod_mam:
    default: always
  mod_muc:
    host: "conference.@HOST@"
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
    history_size: 50
    default_room_options:
      persistent: true
  ## mod_muc_log: {}
  ## mod_multicast: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  ## mod_pres_counter:
  ##   count: 5
  ##   interval: 60
  mod_privacy: {}
  mod_private: {}
  ## mod_proxy65: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
  mod_push: {}
  mod_push_keepalive: {}
  mod_stream_mgmt: {}
  ## mod_register: {}
  mod_roster: {}
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard: {}
  mod_vcard_ldap: {}
  
  ## mod_http_upload: {}
  ## mod_http_upload_quota: {}

###   ============
###   HOST CONFIG

host_config:
  "xmpp.mydomain.com":
    domain_certfile: "/opt/ejabberd/ssl/xmpp.mydomain.com.pem"

###   =====================
###   SESSION MANAGEMENT DB
sm_db_type: mnesia
```

**Comment by scallopedllama** [comment] 2017-09-19 18:19
Oh sorry, you asked for the log. Unfortunately nothing interesting in there:

```
ejabberd config file exists.
ejabberdctl config file exists.
Starting ejabberd...
tail: cannot open ‘/usr/local/var/log/ejabberd/crash.log’ for reading: No such file or directory
tail: cannot open ‘/usr/local/var/log/ejabberd/error.log’ for reading: No such file or directory
tail: cannot open ‘/usr/local/var/log/ejabberd/erlang.log’ for reading: No such file or directory
tail: ‘/usr/local/var/log/ejabberd/crash.log’ has been replaced with a remote file. giving up on this name
tail: ‘/usr/local/var/log/ejabberd/error.log’ has been replaced with a remote file. giving up on this name
18:02:03.417 [notice] Changed loghwm of /usr/local/var/log/ejabberd/error.log to 100
18:02:03.417 [notice] Changed loghwm of /usr/local/var/log/ejabberd/ejabberd.log to 100
18:02:03.417 [info] Application lager started on node ejabberd@xmpp
18:02:03.420 [info] Application crypto started on node ejabberd@xmpp
18:02:03.430 [info] Application sasl started on node ejabberd@xmpp
18:02:03.439 [info] Application asn1 started on node ejabberd@xmpp
18:02:03.439 [info] Application public_key started on node ejabberd@xmpp
18:02:03.450 [info] Application ssl started on node ejabberd@xmpp
18:02:03.453 [info] Application p1_utils started on node ejabberd@xmpp
18:02:03.459 [info] Application fast_yaml started on node ejabberd@xmpp
18:02:03.466 [info] Application fast_tls started on node ejabberd@xmpp
18:02:03.474 [info] Application fast_xml started on node ejabberd@xmpp
18:02:03.477 [info] Application stringprep started on node ejabberd@xmpp
18:02:03.481 [info] Application xmpp started on node ejabberd@xmpp
18:02:03.487 [info] Application cache_tab started on node ejabberd@xmpp
18:02:03.499 [info] Application elixir started on node ejabberd@xmpp
18:02:03.512 [info] Loading configuration from /usr/local/etc/ejabberd/ejabberd.yml
18:02:03.551 [warning] Module mod_http_bind is deprecated, use mod_bosh instead
18:02:03.593 [warning] Module mod_vcard_ldap is deprecated, use mod_vcard with 'db_type: ldap' instead
18:02:04.208 [info] Application mnesia started on node ejabberd@xmpp
18:02:04.229 [info] FQDN used to check DIGEST-MD5 SASL authentication: xmpp.mydomain.com
18:02:04.373 [warning] certificate from /opt/ejabberd/ssl/host.pem is invalid: self-signed certificate in the chain
18:02:04.402 [warning] certificate from /opt/ejabberd/ssl/xmpp.mydomain.com.pem is invalid: self-signed certificate in the chain
18:02:04.516 [info] Application inets started on node ejabberd@xmpp
18:02:04.545 [warning] No certificate found matching 'pubsub.xmpp.mydomain.com': strictly configured clients or servers will reject connections with this host
18:02:04.566 [warning] No certificate found matching 'conference.xmpp.mydomain.com': strictly configured clients or servers will reject connections with this host
18:02:04.590 [info] LDAP connection on 0.0.0.0:389
18:02:04.599 [warning] No certificate found matching 'vjud.xmpp.mydomain.com': strictly configured clients or servers will reject connections with this host
18:02:04.613 [info] LDAP connection on 0.0.0.0:389
18:02:04.613 [info] LDAP connection on 0.0.0.0:389
18:02:04.632 [info] Waiting for Mnesia synchronization to complete
18:02:04.632 [info] ejabberd 17.08 is started in the node ejabberd@xmpp in 1.42s
18:02:04.633 [info] Application ejabberd started on node ejabberd@xmpp
18:02:04.633 [info] Start accepting TCP connections at 0.0.0.0:4560 for ejabberd_xmlrpc
18:02:04.634 [info] Start accepting TCP connections at 0.0.0.0:5222 for ejabberd_c2s
18:02:04.634 [info] Start accepting TCP connections at 0.0.0.0:5280 for ejabberd_http
18:17:17.055 [warning] LDAP server closed the connection: 0.0.0.0:389
In State: active
18:17:17.555 [info] LDAP connection on 0.0.0.0:389
```

There isn't ever anything indicating what the failure was.

**Comment by rroemhild** [comment] 2017-11-10 09:23
Hi, do you still have this issue? Something in your configuration is not correct. You can try to stzart the container with more logging enabled. -e "EJABBERD_LOGLEVEL=5"

**Comment by BrianJVarley** [comment] 2017-11-10 10:27
I had the same issue but added but followed this suggestion and the container stays up:

https://github.com/rroemhild/docker-ejabberd/issues/73#issuecomment-157782394

**Comment by scallopedllama** [comment] 2017-11-13 14:35
Hello,

I do still have this issue. Putting the `EJABBERD_LOGLEVEL=5` environment variable in doesn't seem to print anything new from what I posed before. It does a normal startup then is silent if there are no connections until the container dies.

I also tried the suggestion from the post linked to by @BrianJVarley but that also did not help at all.

**Comment by imensen** [comment] 2017-11-27 20:55
Hi,
I had a similar issue. Apparently the xmlrpc connection timedout.
After many restarts I found that dns lookup for xmpp did not match dns lookup for xmpp.foo.com within container. A quick fix was to add xmpp itself to /etc/hosts and my container stays online, e.g., 172.17.0.x xmpp.

Btw. domainname was not set
root@xmpp:/opt/ejabberd# domainname
(none)

**Comment by kevin71020** [comment] 2017-12-20 08:23
@imensen thanks for your info. I had fixed my SSL problem.

**Comment by seigieu** [comment] 2018-01-25 01:37
I have sameproblem.... my main domain is `xx.com` and xmpp is `sub.xx.com`. My container dies after about a minute.
	docker run -d \
		--name "ejabberd" \
		-p 5222:5222 \
		-p 5269:5269 \
		-p 5280:5280 \
		-h 'sub.xx.com' \
		-e "XMPP_DOMAIN=xx.com" \
		-e "EJABBERD_SKIP_MODULES_UPDATE=true" \
		-e "EJABBERD_LOGLEVEL=5" \
		-e "ERLANG_NODE=ejabberd" \
		-e "EJABBERD_ADMINS=admin@xx.com" \
		-e "EJABBERD_USERS=admin@xx.com:mylpassword" \
		-e "TZ=Europe/Warsaw" \
		rroemhild/ejabberd

**Comment by kevin71020** [comment] 2018-01-25 02:15
This is my setting

```
-e "HOST_HOSTNAME=xx.com" \
-e  XMPP_DOMAIN=xmpp.xx.com"
-e "EJABBERD_ADMINS=admin@xmpp.xx.com" \
-e "EJABBERD_USERS=admin@xmpp.xx.com:password" \
```

**Comment by seigieu** [comment] 2018-01-25 06:42
@kevin71020 Thank you. But ain't working :( Still same

**Comment by seigieu** [comment] 2018-01-25 06:46
Also, when I try to create user i get `docker exec ejabberd ejabberdctl register testuser1 localhost pass123
Failed RPC connection to the node ejabberd@xx: nodedown` where `xx` is part from `xx.com`
PS: Was never able to run any command with docker exec since it always said nodedown

**Comment by umutcetinkaya** [comment] 2018-03-02 08:15
+1 I have the same problem.

**Comment by seigieu** [comment] 2018-03-02 11:29
@umutcetinkaya  Unfortunately not...

**Comment by svenuthe** [comment] 2018-03-02 20:25
Could you post the size of the ssl certificate files?
In some cases the host.pem will be overridden with a zero byte file.

**Comment by rroemhild** [comment] 2018-03-02 22:45
I can not reproduce this error with Ubuntu 14.04 and Docker version 1.9.1, build a34a1d5.

What is your system and docker Version?

Am 25. Januar 2018 02:37:01 MEZ schrieb Grzegorz Zawadzki <notifications@github.com>:

**Comment by umutcetinkaya** [comment] 2018-03-03 13:55
I could not find a solution for the container to start itself constantly. Did you find it? I do not understand why it's closing. :( @scallopedllama @rroemhild @imensen @seigieu ??

**Comment by jacksgt** [comment] 2018-03-03 18:32
I, too, have this issue (Docker Swarm setup which makes debugging a bit more difficult), even though I'm using a modified version of this image based on [Debian sid package with ejabberd 18.01](https://packages.debian.org/sid/ejabberd). 

I think @scallopedllama initial suspicion is correct: the RPC connection to the server breaks, therefore `ejabberdctl foreground` returns and the `/usr/sbin/run` script exists which terminates the container.

Launching ejabberd manually via `ejabberdctl foreground` and waiting for 1-2 minutes exhibits the same behaviour. However, the ejabberd server itself is still running (check with `ps aux`). Also, I cannot connect to the server again via `ejabberctl` (`nodedown`), even though the server is running.

**Comment by rroemhild** [comment] 2018-03-04 09:20
Does the example from the README.md work for you? I tested this example on my Ubuntu 14.04 Server with `Docker version 1.9.1, build a34a1d5` and on my Fedora Workstation with `Docker version 17.12.1-ce, build 7390fc6`. On what OS and Docker version you try to run this image?

**Comment by jacksgt** [comment] 2018-03-05 08:57
@rroemhild Yes and no. The _this specific_ example in the README works:
```
docker run -d \
    --name "ejabberd" \
    -p 5222:5222 \
    -p 5269:5269 \
    -p 5280:5280 \
    -h 'xmpp.example.de' \
    -e "XMPP_DOMAIN=example.de" \
    -e "ERLANG_NODE=ejabberd" \
    -e "EJABBERD_ADMINS=admin@example.de admin2@example.de" \
    -e "EJABBERD_USERS=admin@example.de:password1234 admin2@example.de" \
    -e "TZ=Europe/Berlin" \
    rroemhild/ejabberd
```
**But** omitting the `-h xmpp.example.de` options forces Docker to choose a random hostname (BTW, this is always the case in Swarm mode) and then problems shows: the container only stays up for one minute.

**Comment by rroemhild** [comment] 2018-03-05 13:33
I still can't reproduce the error, sorry. Tested local without `-h hostname` and container is up more than `Application xmpp started on node ejabberd@c201e90f1206`. When I've more time I'll test this in our rancher environment.

**Comment by seigieu** [comment] 2018-03-05 17:01
my shows:

	17:51:55.102 [warning] certificate from /opt/ejabberd/ssl/host.pem is invalid: self-signed certificate in the chain
	17:51:55.180 [warning] certificate from /opt/ejabberd/ssl/xxx.com.pem is invalid: self-signed certificate in the chain

	17:51:57.558 [warning] No certificate found matching 'conference.xxx.com': strictly configured clients or servers will reject connections with this host

	17:51:58.190 [warning] No certificate found matching 'upload.xxx.com': strictly configured clients or servers will reject connections with this host

	17:51:58.877 [warning] No certificate found matching 'pubsub.xxx.com': strictly configured clients or servers will reject connections with this host

	17:51:59.299 [warning] No certificate found matching 'irc.xxx.com': strictly configured clients or servers will reject connections with this host

**Comment by jacksgt** [comment] 2018-03-09 15:52
Okay, I think I was able to narrow down the problem further.

This only happens when the value of the `EJABBERD_NODE` environment variable is set and does not match up with the actual hostname of the container (e.g. `ERLANG_NODE=ejabberd@somedomain`). But, setting it to `ejabberd` or `ejabberd@localhost` seems to work fine.

* Debian Sid
* `uname -a: Linux hostname 4.15.0-1-amd64 #1 SMP Debian 4.15.4-1 (2018-02-18) x86_64 GNU/Linux`
* `docker version:`
```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:17:21 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:15:56 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

Little screencast: https://asciinema.org/a/3Zw0l9wq35s5HtBduCbVTa86k

**Comment by jacksgt** [comment] 2018-03-09 17:03
I have rolled out this change (`EJABBERD_NODE=ejabberd@localhost`) on my 'production' swarm cluster, and so far the container is still running (for 15 minutes now).

 @umutcetinkaya @scallopedllama @imensen @seigieu Please report back if this fixes it for you, too.

**Comment by rroemhild** [comment] 2018-03-09 17:33
Hi  @jacksgt, good finding. From the `ejabberdctl.cfg`:

```
#.
#' ERLANG_NODE: Erlang node name
#
# The next variable allows to explicitly specify erlang node for ejabberd
# It can be given in different formats:
# ERLANG_NODE=ejabberd
#   Lets erlang add hostname to the node (ejabberd uses short name in this case)
# ERLANG_NODE=ejabberd@hostname
#   Erlang uses node name as is (so make sure that hostname is a real
#   machine hostname or you'll not be able to control ejabberd)
# ERLANG_NODE=ejabberd@hostname.domainname
#   The same as previous, but erlang will use long hostname
#   (see erl (1) manual for details)
#
# Default: ejabberd@localhost
#
```

the hostname in `EJABBERD_NODE` must be a real hostname.

**Comment by imensen** [comment] 2018-03-09 21:38
@jacksgt, great job. Fixes my issue as well. I can confirm the following:

ERLANG_NODE=ejabberd@xmpp.foo.com => stays online
ERLANG_NODE=ejabberd@localhost => stays online
ERLANG_NODE=ejabberd  => timeout
ERLANG_NODE=ejabberd@xmpp => timeout

Perhaps we should propose "ERLANG_NODE=ejabberd@localhost" in the Quick Start sample ?

**Comment by rroemhild** [comment] 2018-03-09 22:14
If `EJABBERD_NODE=ejabberd` is set erlang add the short hostname. You want this for i.e clustering. If set to `ejabberd@localhost` this only works for a single instance. Looks for me more like a dns problem. What is the hostname if you let ejabberd choose the hostname? Can the container resolve this hostname?

**Comment by jacksgt** [comment] 2018-03-10 18:19
@imensen setting `ERLANG_NODE=ejabberd` did work for me. 

@rroemhild The problem when letting erlang choose the hostname (i.e. setting `ERLANG_NODE=ejabberd`) is it will use the (random) hostname of the container and then refuse to use this database next time, as it is running in a different container with a different hostname. (see [this stackoverflow post](https://stackoverflow.com/questions/34658505/erlang-version-18-0-and-ejabberd-nodename-conflict) for an example of the error message)

**Comment by rroemhild** [comment] 2018-03-10 20:51
That's true @jacksgt. I see the point that with docker this could create confusion. I'll remove the `ERLANG_NODE` env from the example.

**Comment by seigieu** [comment] 2018-03-11 16:42
+1 Works without defining `ERLANG_NODE` 👍

**Comment by umutcetinkaya** [comment] 2018-03-12 21:07
+1 Works , I made  `ERLANG_NODE=ejabberd@localhost`  and problem fixed. 👍Thanks @jacksgt

**Comment by rroemhild** [comment] 2018-03-13 09:41
Thank you all. I close this issue.

**Closed by rroemhild** 2018-03-13 09:41 UTC
